version: '3.3'
services:
   guidking-com-node:
    container_name: guidking.com
    build: .
    command: 'sh -c "npm install && npm start"'
    image: dev-guidking.com
    working_dir: /app
    environment:
      - NODE_ENV=development
      - PORT=8000
    ports:
      - 8000:8000
    tty: true
    # restart: always
